#name: Gh-Page
#
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#
#    steps:
#      - uses: actions/checkout@v2 # Only works with v2
#      - uses: subosito/flutter-action@v1
#      - uses: bluefireteam/flutter-gh-pages@v7
#        with:
#          baseHref: /
#


name: Deploy Flutter Web App to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x  # Replace with your Flutter version

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/flutter-web-image-viewer/"

  mac-build:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Build Flutter iOS
        run: flutter build ios --release

  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.x

      - name: Build Flutter Windows
        run: flutter build windows --release



#    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#
#      - name: Setup Flutter
#        uses: subosito/flutter-action@v1
#        with:
#          flutter-version: 3.x  # Replace with your Flutter version
#
#      - name: Build Web App
#        run: flutter build web --release --base-href="/flutter-web-image-viewer/"
#
#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          branch: main
#          folder: build/web

